"""empty message

Revision ID: f9849052da5c
Revises: 
Create Date: 2021-04-08 18:10:54.546958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9849052da5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('designation', sa.String(length=50), nullable=True))
    op.drop_column('employee', 'privilege_level')
    op.add_column('online_user', sa.Column('privilege_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('online_user', 'privilege_level')
    op.add_column('employee', sa.Column('privilege_level', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('employee', 'designation')
    # ### end Alembic commands ###
